language: python

addons:
  postgresql: "9.4"

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO="django==1.6.11 django-uuidfield"
  - DJANGO="django==1.8.2"

install:
  - pip install $DJANGO
  - pip install celery geopy mock psycopg2 --use-mirrors
  - export PYTHONPATH=.

script:
  - python geocode/runtests/runtests.py

before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -d travis -U postgres
