language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO="django==1.6.11 --use-mirrors"
  - DJANGO="django==1.8.2 --use-mirrors"

install:
  - pip install $DJANGO
  - pip install celery geopy mock psycopg2 --use-mirrors
  - export PYTHONPATH=.

script:
  - python geocode/runtests/runtests.py
